### ISSUE TITLE
This repository contains Data for ther auto Updater

### ISSUE THREAD

**Issue by ghost** [ClearSkyTeam/ClearSkyStable#2]
This repository contains Data for ther auto Updater

fixed:
This repository contains Data for **the** auto Updater

Hehe, just saw it got updated about 1m ago

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSkyStable/pull/1

**Comment by ghost** [comment]
The TITLE...
![captura](https://cloud.githubusercontent.com/assets/14338036/13979289/02e5e0d0-f09d-11e5-8101-234452803175.PNG)

**Comment by robske110** [comment]
Fixed

**Comment by Aericio** [comment]
I didn't want to make a new issue on this, so I am just asking... are you going to update this repo?

**Comment by robske110** [comment]
Why should I?

**Comment by Aericio** [comment]
idk, when is the cs auto-updater going to be finished?

**Comment by robske110** [comment]
The new one? When minecarts and inv related stuff is done. The auto updater has low priority

**Comment by Aericio** [comment]
Ahh, okay. 
(to be honest, auto-updaters are annoying.)
